# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26ba454d546ef28fcf96b81c2ec06de26dbd4e0b8de9db5ecfc3fc10e87e0177ac7466fd211fdcb8550ce7c4b1c0708f63070cdf7bb5f7ee764d5d6593cc160f

test:
  secret_key_base: 391046a518b56ca3d11cd859f83b83a57dfa43a4f127c8e562b48b79ed2da6466cf16a01b0d5b6523e624f30cccb0e3bdb894bec512c20da4e008d3dc849c981

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
